-- ========================================================
-- THAKRUTHA 2026 (താക്കൃഥ) Complete Supabase Reset Script
-- Copy & Paste this entire script into Supabase SQL Editor
-- (https://supabase.com/dashboard/project/_/sql/new)
-- ========================================================

-- 1. DROP Existing Tables for a Clean Fresh Start
DROP TABLE IF EXISTS public.tickets CASCADE;
DROP TABLE IF EXISTS public.settings CASCADE;

-- 2. CREATE Fresh Tickets Table (All Production Fields)
CREATE TABLE public.tickets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_code TEXT UNIQUE,
  ticket_code TEXT UNIQUE,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT NOT NULL,
  emergency_contact TEXT NOT NULL,
  pass_type TEXT NOT NULL DEFAULT 'THAKRUTHA Stag Festival Pass',
  amount NUMERIC NOT NULL DEFAULT 1100,
  utr_number TEXT DEFAULT '',
  payment_screenshot TEXT DEFAULT '',
  status TEXT DEFAULT 'PENDING',
  sadhya_type TEXT DEFAULT '100% Pure Veg',
  submitted_at TEXT,
  approved_at TEXT,
  approved_by TEXT,
  checked_in INT DEFAULT 0,
  check_in_time TEXT,
  created_at TEXT DEFAULT NOW()
);

-- 3. CREATE Settings Table (UPI QR & Dynamic Options)
CREATE TABLE public.settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

-- 4. INSERT Default Settings
INSERT INTO public.settings (key, value) VALUES
  ('upi_qr_url', 'images/upi_qr.png'),
  ('upi_id', 'thakrutha@upi')
ON CONFLICT (key) DO NOTHING;

-- 5. DISABLE RLS & Grant Full Access (Eliminates permission/visibility bugs)
ALTER TABLE public.tickets DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings DISABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.tickets TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.settings TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;

-- 6. Reload Supabase Schema Cache Instantly
NOTIFY pgrst, 'reload schema';
