-- ========================================================
-- THAKRUTHA 2026 (താക്കൃഥ) Supabase Database Migration
-- Run this script in your Supabase SQL Editor (https://app.supabase.com)
-- ========================================================

-- 1. Create Tickets Table
CREATE TABLE IF NOT EXISTS public.tickets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_code TEXT UNIQUE,
  ticket_code TEXT UNIQUE,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT NOT NULL,
  emergency_contact TEXT NOT NULL,
  pass_type TEXT NOT NULL DEFAULT 'THAKRUTHA Stag Festival Pass',
  amount NUMERIC NOT NULL DEFAULT 1100,
  utr_number TEXT DEFAULT '',
  payment_screenshot TEXT DEFAULT '',
  status TEXT DEFAULT 'PENDING',
  sadhya_type TEXT DEFAULT '100% Pure Veg',
  submitted_at TEXT,
  approved_at TEXT,
  approved_by TEXT,
  checked_in INT DEFAULT 0,
  check_in_time TEXT,
  created_at TEXT DEFAULT NOW()
);

-- Add column if table already exists
ALTER TABLE public.tickets ADD COLUMN IF NOT EXISTS payment_screenshot TEXT DEFAULT '';

-- 2. Create Settings Table
CREATE TABLE IF NOT EXISTS public.settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

-- 3. Insert Default Settings
INSERT INTO public.settings (key, value) VALUES
  ('upi_qr_url', 'images/upi_qr.png'),
  ('upi_id', 'thakrutha@upi')
ON CONFLICT (key) DO NOTHING;

-- 4. Enable Row Level Security (RLS) & Add Public Policies
ALTER TABLE public.tickets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public Select Settings" ON public.settings FOR SELECT USING (true);
CREATE POLICY "Public Insert Tickets" ON public.tickets FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Select Tickets" ON public.tickets FOR SELECT USING (true);
CREATE POLICY "Public Update Tickets" ON public.tickets FOR UPDATE USING (true);
CREATE POLICY "Public Update Settings" ON public.settings FOR UPDATE USING (true);
